describe('PT-12: Kompletni acceptance flow', () => {
  it('Korisnik se registrira, prijavi, kreira rezervaciju, odjavi - fotograf zaprimi rezervaciju', () => {
    const timestamp = Date.now()
    const email = `flow${timestamp}@test.com`

    cy.visit('http://localhost:9000/#/auth')
    cy.get('input[aria-label="Ime"]').type('Flow')
    cy.get('input[aria-label="Prezime"]').type('Test')
    cy.get('input[aria-label="E-mail adresa"]').last().type(email)
    cy.get('input[type="password"]').last().type('test123')
    cy.contains('button', 'Registriraj se').click()
    cy.get('.q-notification').should('contain', 'uspješna')
    cy.wait(1000)

    cy.get('input[aria-label="E-mail adresa"]').first().clear().type(email)
    cy.get('input[type="password"]').first().clear().type('test123')
    cy.contains('button', 'Prijavi se').click()
    cy.url().should('include', '/korisnik')
    cy.wait(1000)

    cy.visit('http://localhost:9000/#/korisnik/usluge')
    cy.wait(2000)
    cy.get('.card-line').should('have.length.greaterThan', 0)

    cy.visit('http://localhost:9000/#/korisnik/rezervacija')
    cy.wait(1000)
    cy.get('.q-select').first().click()
    cy.get('.q-menu .q-item').first().click({ force: true })
    cy.wait(500)
    cy.get('.q-select').eq(1).click()
    cy.get('.q-menu .q-item').first().click({ force: true })
    cy.wait(500)
    cy.get('input[type="date"]').type('2028-12-01')
    cy.get('input[type="time"]').type('16:00')
    cy.contains('.q-field', 'Lokacija').find('input').type('Bosnaka 1, Split')
    cy.contains('.q-field', 'Dodatne napomene').find('textarea').type('Testna napomena')
    cy.contains('button', 'Potvrdi rezervaciju').click()
    cy.get('.q-notification').should('exist')
    cy.wait(1000)

    cy.contains('Odjava').click()
    cy.url().should('include', '/')
    cy.wait(1000)

    cy.visit('http://localhost:9000/#/auth')
    cy.get('input[aria-label="E-mail adresa"]').first().type('marko.kovac@studio.hr')
    cy.get('input[type="password"]').first().type('fotograf123')
    cy.contains('button', 'Prijavi se').click()
    cy.url().should('include', '/fotograf')
    cy.wait(1000)

    cy.visit('http://localhost:9000/#/fotograf/rezervacije')
    cy.wait(2000)
    cy.get('.q-table').should('exist')
    cy.get('.q-table tbody tr').should('have.length.greaterThan', 0)
    cy.contains('Pregled detalja').first().click()
    cy.wait(1000)
    cy.get('.q-dialog, .ee-page').should('exist')
  })
})